services:
  
  wireguard-dashboard:
    build: ./
    container_name: wiregate
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    environment:
      - wg_net=10.0.0.1/24
      - wg_port=51820
    volumes:
      - wgd_configs:/etc/wireguard
      - wgd_app:/opt/wireguarddashboard/src
    ports:
      - 10086:10086/tcp
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
   

volumes:
    wgd_configs:
    wgd_app: